# Generated by Django 5.0.1 on 2024-03-15 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('allergy_id', models.AutoField(primary_key=True, serialize=False)),
                ('allergy_name', models.CharField(max_length=255)),
                ('allergy_type', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('allergic_reaction', models.CharField(max_length=255)),
                ('comments', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'allergies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateField()),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'appointment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('diagnosis_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('diagnosis', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'diagnosis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_fname', models.CharField(db_column='doctor_fname', max_length=255)),
                ('doctor_lname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=1)),
                ('doctor_contact_no', models.BigIntegerField()),
                ('address', models.CharField(max_length=255)),
                ('license_no', models.BigIntegerField()),
                ('specialty', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'doctor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorPatient',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'doctor_patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HeartRate',
            fields=[
                ('heart_rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetaken', models.DateField()),
                ('heart_rate', models.IntegerField()),
                ('comments', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'heart_rate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('immu_id', models.AutoField(primary_key=True, serialize=False)),
                ('immu_name', models.CharField(max_length=255)),
                ('datetime', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('comments', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'immunizations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medications_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'medications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_fname', models.CharField(max_length=255)),
                ('patient_lname', models.CharField(max_length=255)),
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_dob', models.DateField()),
                ('patient_gender', models.CharField(max_length=1)),
                ('patient_contact_no', models.BigIntegerField()),
                ('emer_contact_name', models.CharField(max_length=255)),
                ('emer_contact_no', models.BigIntegerField()),
                ('address', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=255)),
                ('medications', models.CharField(max_length=255)),
                ('instructions', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'prescription',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(max_length=255)),
                ('report_file', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RespirationRate',
            fields=[
                ('resp_rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetaken', models.DateField()),
                ('resp_rate', models.IntegerField()),
                ('comments', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'respiration_rate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('surgery_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('surgeon', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'surgery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=255)),
                ('test_description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestAppointment',
            fields=[
                ('test_appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_datetime', models.DateField()),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'test_appointment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('test_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_report_date', models.DateField()),
                ('test_report_file', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'test_report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('vitalsign_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vitalsign',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_number', models.CharField(max_length=255)),
                ('coordinates', models.CharField(max_length=255)),
                ('loc_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('blood_press_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateField()),
                ('blood_press', models.CharField(max_length=255)),
                ('comments', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='cureme.patient')),
            ],
            options={
                'db_table': 'blood_pressure',
            },
        ),
        migrations.CreateModel(
            name='Oxygen',
            fields=[
                ('oxygen_id', models.AutoField(primary_key=True, serialize=False)),
                ('oxygen_rate', models.IntegerField()),
                ('datetime', models.DateField()),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='cureme.patient')),
            ],
            options={
                'db_table': 'oxygen',
            },
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('temp_id', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.IntegerField()),
                ('datetime', models.DateField()),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='cureme.patient')),
            ],
            options={
                'db_table': 'temperature',
            },
        ),
    ]
