# Generated by Django 5.0.1 on 2024-03-15 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cureme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insulin',
            fields=[
                ('insulin_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('blood_sugar', models.CharField(max_length=255)),
                ('comments', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(db_column='patient', on_delete=django.db.models.deletion.CASCADE, to='cureme.patient')),
            ],
            options={
                'db_table': 'insulin',
            },
        ),
        migrations.DeleteModel(
            name='Allergy',
        ),
        migrations.DeleteModel(
            name='Immunization',
        ),
        migrations.DeleteModel(
            name='Medication',
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='patient',
            field=models.ForeignKey(db_column='patient', on_delete=django.db.models.deletion.CASCADE, to='cureme.patient'),
        ),
        migrations.AlterField(
            model_name='oxygen',
            name='patient',
            field=models.ForeignKey(db_column='patient', on_delete=django.db.models.deletion.CASCADE, to='cureme.patient'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='patient',
            field=models.ForeignKey(db_column='patient', on_delete=django.db.models.deletion.CASCADE, to='cureme.patient'),
        ),
        migrations.AlterModelTable(
            name='room',
            table='room',
        ),
    ]
